apiVersion: v1
appVersion: 4.0.0
description: Helm chart for NeuVector's neuvector services
engine: gotpl
home: https://neuvector.com
icon: https://avatars2.githubusercontent.com/u/19367275?s=200&v=4
maintainers:
- email: support@neuvector.com
  name: becitsthere
name: neuvector
version: 1.6.9
